# Generated by Django 4.2.7 on 2024-04-11 06:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, choices=[('Advanced', 'Advanced'), ('Normal', 'Normal')], default='Normal', max_length=100, null=True)),
                ('guarantee_world_insurer', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('overdue120', models.FloatField(blank=True, default=0, null=True)),
                ('grant_period', models.FloatField(default=0)),
                ('pause', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Balances',
            },
        ),
        
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=40)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('inv_amount', models.FloatField(blank=True, null=True)),
                ('cycle1', models.FloatField(blank=True, default=0, null=True)),
                ('cycle2', models.FloatField(blank=True, default=0, null=True)),
                ('cycle3', models.FloatField(blank=True, default=0, null=True)),
                ('cycle4', models.FloatField(blank=True, default=0, null=True)),
                ('cycle5', models.FloatField(blank=True, default=0, null=True)),
                ('cycle6', models.FloatField(blank=True, default=0, null=True)),
                ('cycle7', models.FloatField(blank=True, default=0, null=True)),
                ('cycle8', models.FloatField(blank=True, default=0, null=True)),
                ('cycle9', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(default=datetime.datetime(2024, 4, 11, 9, 30))),
                ('type', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], max_length=20)),
                ('action_type', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Call', 'Call')], max_length=20)),
                ('action_amount', models.FloatField()),
                ('subtype', models.CharField(blank=True, choices=[('Reminder', 'Reminder'), ('Gentle', 'Gentle'), ('Strong', 'Strong'), ('Final', 'Final')], max_length=20, null=True)),
                ('followup_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collector', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
                ('collector', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account_name', 'date')},
            },
        ),
    ]
