# Generated by Django 4.2.7 on 2024-04-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_action_action_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditentry',
            name='settle',
            field=models.BooleanField(default=False),
        ),
    ]
