# Generated by Django 4.2.7 on 2024-03-04 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_alter_client_grant_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 9, 30)),
        ),
    ]
