# Generated by Django 4.2.7 on 2024-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_alter_action_action_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='extended_date',
        ),
        migrations.AddField(
            model_name='client',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
