# Generated by Django 4.2.7 on 2024-03-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_remove_action_extended_date_client_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='completed',
            new_name='pause',
        ),
    ]
