# Generated by Django 4.2.7 on 2024-04-24 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_rename_short_name_bill_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='short_name',
            new_name='account_name',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 9, 30)),
        ),
    ]
