# Generated by Django 4.2.7 on 2024-04-29 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_alter_action_action_date_creditentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 9, 30)),
        ),
    ]
