# Generated by Django 4.2.7 on 2024-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_alter_action_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditentry',
            name='collector',
            field=models.CharField(default=None),
        ),
    ]
