# Generated by Django 4.2.7 on 2024-04-29 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0048_alter_creditentry_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditentry',
            name='collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
