# Generated by Django 4.2.7 on 2024-06-17 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_alter_creditentry_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 9, 30)),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
